/**
 * FluxNotes Treatment Options Rest Client
 * FluxNotes Treatment Options Rest Client
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FluxNotesTreatmentOptionsRestClient) {
      root.FluxNotesTreatmentOptionsRestClient = {};
    }
    root.FluxNotesTreatmentOptionsRestClient.TreatmentOptions = factory(root.FluxNotesTreatmentOptionsRestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TreatmentOptions model module.
   * @module model/TreatmentOptions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TreatmentOptions</code>.
   * @alias module:model/TreatmentOptions
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>TreatmentOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TreatmentOptions} obj Optional instance to populate.
   * @return {module:model/TreatmentOptions} The populated <code>TreatmentOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('disease')) {
        obj['disease'] = ApiClient.convertToType(data['disease'], 'String');
      }
      if (data.hasOwnProperty('race')) {
        obj['race'] = ApiClient.convertToType(data['race'], 'String');
      }
      if (data.hasOwnProperty('isAlive')) {
        obj['isAlive'] = ApiClient.convertToType(data['isAlive'], 'String');
      }
      if (data.hasOwnProperty('survivalMonths')) {
        obj['survivalMonths'] = ApiClient.convertToType(data['survivalMonths'], 'Number');
      }
      if (data.hasOwnProperty('dxGrade')) {
        obj['dxGrade'] = ApiClient.convertToType(data['dxGrade'], 'String');
      }
      if (data.hasOwnProperty('treatOptions')) {
        obj['treatOptions'] = ApiClient.convertToType(data['treatOptions'], 'String');
      }
    }
    return obj;
  }

  /**
   * disease filter
   * @member {String} disease
   */
  exports.prototype['disease'] = undefined;
  /**
   * race filter
   * @member {String} race
   */
  exports.prototype['race'] = undefined;
  /**
   * dead or alive
   * @member {String} isAlive
   */
  exports.prototype['isAlive'] = undefined;
  /**
   * survival time in months
   * @member {Number} survivalMonths
   */
  exports.prototype['survivalMonths'] = undefined;
  /**
   * grade of the disease to filter
   * @member {String} dxGrade
   */
  exports.prototype['dxGrade'] = undefined;
  /**
   * treatment option recieved
   * @member {String} treatOptions
   */
  exports.prototype['treatOptions'] = undefined;



  return exports;
}));


